version: "3.8"

services:
  maria-db:
    image: mariadb
    volumes:
      - ./data:/var/lib/mysql           # Persiste datele bazei de date
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql    
    restart: unless-stopped
    tty: true
    ports:
      - 3308:3306  # Expune portul 3306 al containerului la portul 3308 al gazdei
    environment:
      MARIADB_ROOT_PASSWORD: pass1234  # Parola root pentru MariaDB
      MARIADB_DATABASE: myapp  # Creează baza de date 'myapp'
      MARIADB_USER: admin  # Creează utilizatorul 'admin'
      MARIADB_PASSWORD: admin_password  # Parola utilizatorului 'admin'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]  # Verifică sănătatea serviciului
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      provedb:
        ipv4_address: 10.10.0.2

  python-app:
    build: .
    ports:
      - 5000:5000  # Expune portul 5000 pentru aplicația Flask
    depends_on:
      - maria-db
    entrypoint: ["./wait-for-it.sh", "maria-db:3306", "--", "flask", "run", "--host=0.0.0.0", "--port=5000"]
    networks:
      provedb:
        ipv4_address: 10.10.0.3

networks:
  provedb:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/16
          gateway: 10.10.0.1
